server :
  port : 8091
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:daman;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    show-sql: false
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop